server:
  port: 8084

spring:
  application:
    name: pedir-citas
  datasource:
    url: jdbc:mysql://localhost:3306/db_pedircitasmedicas?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true